#include "art/mm.hpp"

namespace art::mm {
    extern "C" char _kernelhalfvstart, _kernelhalfvend;
    extern "C" char _boot_text_start;
    extern "C" char _boot_text_vstart;
    extern "C" char _boot_text_end;
    extern "C" char _boot_text_vend;
    extern "C" char _boot_rodata_start;
    extern "C" char _boot_rodata_vstart;
    extern "C" char _boot_rodata_end;
    extern "C" char _boot_rodata_vend;
    extern "C" char _boot_data_start;
    extern "C" char _boot_data_vstart;
    extern "C" char _boot_data_end;
    extern "C" char _boot_data_vend;
    extern "C" char _boot_bss_start;
    extern "C" char _boot_bss_vstart;
    extern "C" char _boot_bss_end;
    extern "C" char _boot_bss_vend;
    extern "C" char _kernel_text_start;
    extern "C" char _kernel_text_vstart;
    extern "C" char _kernel_text_end;
    extern "C" char _kernel_text_vend;
    extern "C" char _kernel_rodata_start;
    extern "C" char _kernel_rodata_vstart;
    extern "C" char _kernel_rodata_end;
    extern "C" char _kernel_rodata_vend;
    extern "C" char _kernel_data_start;
    extern "C" char _kernel_data_vstart;
    extern "C" char _kernel_data_end;
    extern "C" char _kernel_data_vend;
    extern "C" char _kernel_bss_start;
    extern "C" char _kernel_bss_vstart;
    extern "C" char _kernel_bss_end;
    extern "C" char _kernel_bss_vend;
    extern "C" char _kernel_init_start;
    extern "C" char _kernel_init_vstart;
    extern "C" char _kernel_init_end;
    extern "C" char _kernel_init_vend;

    addr_t kernelhalf_start     = (addr_t) &_kernelhalfvstart;
    addr_t kernelhalf_end       = (addr_t) &_kernelhalfvend;
    phys_t boot_text_start      = (phys_t) &_boot_text_start;
    addr_t boot_text_vstart     = (addr_t) &_boot_text_vstart;
    phys_t boot_text_end        = (phys_t) &_boot_text_end;
    addr_t boot_text_vend       = (addr_t) &_boot_text_vend;
    phys_t boot_rodata_start    = (phys_t) &_boot_rodata_start;
    addr_t boot_rodata_vstart   = (addr_t) &_boot_rodata_vstart;
    phys_t boot_rodata_end      = (phys_t) &_boot_rodata_end;
    addr_t boot_rodata_vend     = (addr_t) &_boot_rodata_vend;
    phys_t boot_data_start      = (phys_t) &_boot_data_start;
    addr_t boot_data_vstart     = (addr_t) &_boot_data_vstart;
    phys_t boot_data_end        = (phys_t) &_boot_data_end;
    addr_t boot_data_vend       = (addr_t) &_boot_data_vend;
    phys_t boot_bss_start       = (phys_t) &_boot_bss_start;
    addr_t boot_bss_vstart      = (addr_t) &_boot_bss_vstart;
    phys_t boot_bss_end         = (phys_t) &_boot_bss_end;
    addr_t boot_bss_vend        = (addr_t) &_boot_bss_vend;
    phys_t kernel_text_start    = (phys_t) &_kernel_text_start;
    addr_t kernel_text_vstart   = (addr_t) &_kernel_text_vstart;
    phys_t kernel_text_end      = (phys_t) &_kernel_text_end;
    addr_t kernel_text_vend     = (addr_t) &_kernel_text_vend;
    phys_t kernel_rodata_start  = (phys_t) &_kernel_rodata_start;
    addr_t kernel_rodata_vstart = (addr_t) &_kernel_rodata_vstart;
    phys_t kernel_rodata_end    = (phys_t) &_kernel_rodata_end;
    addr_t kernel_rodata_vend   = (addr_t) &_kernel_rodata_vend;
    phys_t kernel_data_start    = (phys_t) &_kernel_data_start;
    addr_t kernel_data_vstart   = (addr_t) &_kernel_data_vstart;
    phys_t kernel_data_end      = (phys_t) &_kernel_data_end;
    addr_t kernel_data_vend     = (addr_t) &_kernel_data_vend;
    phys_t kernel_bss_start     = (phys_t) &_kernel_bss_start;
    addr_t kernel_bss_vstart    = (addr_t) &_kernel_bss_vstart;
    phys_t kernel_bss_end       = (phys_t) &_kernel_bss_end;
    addr_t kernel_bss_vend      = (addr_t) &_kernel_bss_vend;
    phys_t kernel_init_start    = (phys_t) &_kernel_init_start;
    addr_t kernel_init_vstart   = (addr_t) &_kernel_init_vstart;
    phys_t kernel_init_end      = (phys_t) &_kernel_init_end;
    addr_t kernel_init_vend     = (addr_t) &_kernel_init_vend;
}